<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="images\Board\board.png" />
    <None Remove="images\figures\black-elephant.png" />
    <None Remove="images\figures\black-horse.png" />
    <None Remove="images\figures\black-king.png" />
    <None Remove="images\figures\black-queen.png" />
    <None Remove="images\figures\black-ship.png" />
    <None Remove="images\figures\black-soldier.png" />
    <None Remove="images\figures\white-elephant.png" />
    <None Remove="images\figures\white-horse.png" />
    <None Remove="images\figures\white-king.png" />
    <None Remove="images\figures\white-queen.png" />
    <None Remove="images\figures\white-ship.png" />
    <None Remove="images\figures\white-soldier.png" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ClassLibrary1\Chessuniverse.Library.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="images\Board\board.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\figures\black-elephant.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\figures\black-horse.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\figures\black-king.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\figures\black-queen.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\figures\black-ship.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\figures\black-soldier.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\figures\white-elephant.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\figures\white-horse.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\figures\white-king.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\figures\white-queen.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\figures\white-ship.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
    <Resource Include="images\figures\white-soldier.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
